name: spatialalign
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.13.5=h4612cfd_100_cp313
  - python_abi=3.13=0_cp313
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py313h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.8.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - attrs==25.3.0
      - av==16.1.0
      - blessed==1.21.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - contourpy==1.3.3
      - controlnet-aux==0.0.7
      - cupy-cuda12x==13.4.1
      - cycler==0.12.1
      - defusedxml==0.7.1
      - einops==0.8.1
      - fastrlock==0.8.3
      - filelock==3.18.0
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - ftfy==6.3.1
      - gpustat==1.1.1
      - grpcio==1.73.1
      - hf-xet==1.1.5
      - huggingface-hub==0.33.0
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - iopath==0.1.10
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - lightning==2.5.2
      - lightning-utilities==0.14.3
      - markdown==3.8.2
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - modelscope==1.27.1
      - mpmath==1.3.0
      - multidict==6.6.3
      - networkx==3.5
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.3.0
      - peft==0.15.2
      - pillow==11.2.1
      - piq==0.8.0
      - portalocker==3.2.0
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.5.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scipy==1.16.0
      - sentencepiece==0.2.1
      - six==1.17.0
      - supervision==0.26.1
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tifffile==2025.6.11
      - timm==1.0.15
      - tokenizers==0.20.3
      - torch==2.7.1
      - torchmetrics==1.7.4
      - torchvision==0.22.1
      - tqdm==4.67.1
      - transformers==4.46.2
      - triton==3.3.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - yarl==1.20.1
      - zipp==3.23.0

